export const COURSE = {
  id: 'foundation',
  title: "Let's Create Foundation!",
  description: "Everything you need to know to get started at AMRYTT MEDIA LLC.",
  totalLessons: 5,
  modules: [
    {
      id: 1,
      title: 'Introduction to AMRYTT MEDIA LLC',
      emoji: '🏢',
      color: 'from-indigo-500 to-blue-600',
      lightColor: 'bg-indigo-50',
      borderColor: 'border-indigo-200',
      lessons: [
        { id: 1, title: 'History & Overview', duration: null },
        { id: 2, title: 'Vision, Mission & Core Values', duration: null },
        { id: 3, title: 'Goals & Objectives', duration: null },
        { id: 4, title: 'AMRYTT MEDIA Philosophy', duration: null },
        { id: 5, title: 'Key Departments of AMRYTT MEDIA', duration: null },
      ],
    },
    {
      id: 2,
      title: 'Comprehensive Guide to Digital Marketing',
      emoji: '📈',
      color: 'from-violet-500 to-purple-600',
      lightColor: 'bg-violet-50',
      borderColor: 'border-violet-200',
      lessons: [
        { id: 6, title: 'Introduction, Key Components, Evolution', duration: null },
        { id: 7, title: 'Importance & The Future of Digital Marketing', duration: null },
        { id: 8, title: 'What is Content Marketing?', duration: null },
        { id: 9, title: 'What is Guest Posting?', duration: null },
        { id: 10, title: 'Test: Digital, Content Marketing & Guest Posting', duration: null, isQuiz: true },
        { id: 11, title: 'Key Terminologies in Content Marketing-1', duration: null },
        { id: 12, title: 'Test: Key Terminologies-1', duration: null, isQuiz: true },
        { id: 13, title: 'Key Terminologies in Content Marketing-2', duration: null },
        { id: 14, title: 'Test: Key Terminologies-2', duration: null, isQuiz: true },
        { id: 15, title: 'Key Terminologies in Content Marketing-3', duration: null },
        { id: 16, title: 'Test: Key Terminologies-3', duration: null, isQuiz: true },
        { id: 17, title: 'Key Terminologies in Content Marketing-4', duration: null },
        { id: 18, title: 'Test: Key Terminologies-4', duration: null, isQuiz: true },
        { id: 19, title: 'Key Terminologies in Content Marketing-5', duration: null },
        { id: 20, title: 'Test: Key Terminologies-5', duration: null, isQuiz: true },
        { id: 21, title: 'Key Terminologies in Content Marketing-6', duration: null },
        { id: 22, title: 'Test: Key Terminologies-6', duration: null, isQuiz: true },
        { id: 23, title: 'Key Terminologies in Content Marketing-7', duration: null },
        { id: 24, title: 'Test: Key Terminologies-7', duration: null, isQuiz: true },
      ],
    },
    {
      id: 3,
      title: 'Introduction to GUESTPOSTLINKS.NET',
      emoji: '🔗',
      color: 'from-emerald-500 to-teal-600',
      lightColor: 'bg-emerald-50',
      borderColor: 'border-emerald-200',
      lessons: [
        { id: 25, title: 'GUESTPOSTLINKS.NET & Its Philosophy', duration: null },
        { id: 26, title: 'Key Services: Link Building & Local SEO', duration: null },
        { id: 27, title: 'Test: Final Assessment', duration: null, isQuiz: true },
        { id: 28, title: 'SOP: Payment Methods, Fees & How to Handle Them', duration: null },
      ],
    },
    {
      id: 4,
      title: 'SEO Interactive Playground',
      emoji: '🎮',
      color: 'from-rose-500 to-orange-500',
      lightColor: 'bg-rose-50',
      borderColor: 'border-rose-200',
      alwaysUnlocked: true,
      lessons: [
        { id: 29, title: 'Interactive SEO Playground — 8 Stations', duration: null },
      ],
    },
  ],
}
